"""
Create a program that will play the “cows and bulls” game with the user. The game works like this:
Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. For every digit that the
user guessed correctly in the correct place, they have a “cow”. For every digit the user guessed
correctly in the wrong place is a “bull.” Every time the user makes a guess, tell them how many
“cows” and “bulls” they have. Once the user guesses the correct number, the game is over. Keep track
of the number of guesses the user makes throughout teh game and tell the user at the end.
Say the number generated by the computer is 1038. An example interaction could look like this:
  Welcome to the Cows and Bulls Game!
  Enter a number:
  >>> 1234
  2 cows, 0 bulls
  >>> 1256
  1 cow, 1 bull
  ...
"""

import random

def compare_numbers(number, user_guess):
    cowbull = [0,0] #cows, then bulls
    for i in range(len(number)):
        if number[i] == user_guess[i]:
            cowbull[1]+=1
        else:
            cowbull[0]+=1
    return cowbull

if __name__=="__main__":
    playing = True #gotta play the game
    number = str(random.randint(0,9999)) #random 4 digit number
    guesses = 0

    print("Jugaremos juego llamado Cowbull!") #explanation
    print("Yo generaré un numero de 4 digitos, y tú tienes que adivinar los numeros un digito a la vez.")
    print("Por cada numero adivinado en la posicion incorrecta, ganas 1 cow. Por cada numero correcto en la posicion correcta, ganas 1 bull.")
    print("El juego termina cuando obtienes 4 bulls!")
    print("Escribe exit para salir en cualquier momento. \n")

    while playing:
        user_guess = input("Dame tu mejor numero: ")
        if user_guess == "exit":
            break
        cowbullcount = compare_numbers(number,user_guess)
        guesses+=1

        print("Tú tienes "+ str(cowbullcount[0]) + " cows, y " + str(cowbullcount[1]) + " bulls.\n")

        if cowbullcount[1]==4:
            playing = False
            print("Ganaste el juego despues de " + str(guesses) + "! El numero fue "+str(number))
            break #redundant exit
        else:
            print("Tu numero aun no es correcto, intenta de nuevo.")